### ISSUE TITLE
võiks mingi piltide jama ka korda ajada, igal loomal pilt jne

### ISSUE THREAD

**Issue by ClevenL** [henrivajak/php-ruhmatoo-projekt#4]

**Comment by ClevenL** [comment]
ma mõtlesin et igale kuulutusele tuleb pilt juurde... kuulutuse lisamisel saab üleslaadida pildi või siis urlist lisada pildi ja kuulutuste lehel on iga looma juures ka tema pilt

**Comment by ClevenL** [comment]
jezuz

**Comment by henrivajak** [comment]
hmmmmmmmmmmm
